# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20170125_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'verbose_name': 'Região', 'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterField(
            model_name='cidade',
            name='ddd',
            field=models.CharField(help_text='Discagem Direta a Distancia', max_length=2, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='nome',
            field=models.CharField(max_length=32, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='sigla',
            field=models.CharField(max_length=2, unique=True, verbose_name='Sigla'),
        ),
    ]
